name: Push Metrics

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Exporter
        run: python prometheus_exporter.py
